Website = "https://github.com/cwxsss/helium_plus"

[Details]
  Icon = "assets/img/helium_updater.png"
  Name = "helium_updater"
  ID = "com.github.cwxsss.helium_updater"
  Version = "0.1.14"
  Build = 0
