name: Build

on:
  push:
    branches: [main, master]
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  windows-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: WillAbides/setup-go-faster@v1.19.0
        with:
          go-version: stable

      - name: Setup Env
        run: >-
          sudo apt-get update &&
          sudo apt-get install -y
          bc gcc libgl1-mesa-dev libwayland-dev libx11-dev libxkbcommon-dev xorg-dev xvfb unzip zip

      - name: Setup fyne-cross
        run: go install github.com/fyne-io/fyne-cross@latest

      - name: Build
        run: |
          fyne-cross windows -arch=amd64

      - name: Package
        run: |
          mkdir -p dist fyne-cross/dist/windows-amd64/unpacked
          unzip fyne-cross/dist/windows-amd64/helium_updater.exe.zip -d fyne-cross/dist/windows-amd64/unpacked
          zip -rj dist/helium_updater-windows-amd64.zip fyne-cross/dist/windows-amd64/unpacked/helium_updater.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: helium_updater-windows-amd64
          path: dist/helium_updater-windows-amd64.zip

      - name: Attach To Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/helium_updater-windows-amd64.zip
